# Initially copied from https://github.com/jkehres/docker-compose-influxdb-grafana

version: '2'
services:

  influxdb:
    image: influxdb:1.8.5 # v2.x requires a different configuration
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sandbox
      - INFLUXDB_ADMIN_USER=sandbox
      - INFLUXDB_ADMIN_PASSWORD=sandbox

  chronograf:
    image: chronograf:1.8
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage: