management:
  endpoint:
    env:
      post:
        enabled: true
spring:
  config:
    import:
      - shared/for-microservices.yaml
      - feature_config/properties-state.yaml
      - feature_config/encrypted-properties.yaml