{
 "title": "Resilience4j dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Circuit Breaker state",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "closed",
     "measurement": "resilience4j_circuitbreaker_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "closed" }
     ]
    },
    {
     "alias": "open",
     "measurement": "resilience4j_circuitbreaker_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "open" }
     ]
    },
    {
     "alias": "half-open",
     "measurement": "resilience4j_circuitbreaker_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "half_open" }
     ]
    }
   ]
  },
  {
   "title": "Number per 10 seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "successful",
     "measurement": "resilience4j_circuitbreaker_calls",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "successful" }
     ]
    },
    {
     "alias": "failed",
     "measurement": "resilience4j_circuitbreaker_calls",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "failed" }
     ]
    },
    {
     "alias": "not permitted",
     "measurement": "resilience4j_circuitbreaker_not_permitted_calls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "kind", "operator": "=", "value": "not_permitted" }
     ]
    }
   ]
  },
  {
   "title": " Rate of Slow calls / Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "slow call rate",
     "measurement": "resilience4j_circuitbreaker_slow_call_rate",
     "query": "SELECT sum(\"value\") FROM \"resilience4j_circuitbreaker_slow_call_rate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "failure rate",
     "measurement": "resilience4j_circuitbreaker_failure_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}