logging:
  level:
    org.springframework.security: debug
    org.springframework.security.core.userdetails: error
    root: info
spring:
  application:
    name: spring-cloud-gateway
  config:
    import:
      - shared/for-microservices.yaml
  cloud:
    gateway:
      routes:
        - id: spring-boot
          uri: http://localhost:8082
          predicates:
            - Path=/spring-boot/**
          filters:
            - RewritePath=/spring-boot/?(?<segment>.*), /$\{segment}
        - id: spring-cloud
          uri: http://localhost:8081
          predicates:
            - Path=/spring-cloud/**
          filters:
            - RewritePath=/spring-cloud/?(?<segment>.*), /$\{segment}
      default-filters:
        - Security
management:
  endpoints:
    web:
      exposure:
        include: '*'

custom:
  swagger-ui:
    routes:
      spring-boot:
        contextPath: /spring-boot
      spring-cloud:
        contextPath: /spring-cloud