logging:
  level:
    org.springframework.security: debug
    root: info
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://quiet-star-2981.getsandbox.com:443
          predicates:
            - Path=/{segment}
          filters:
            - Security
management:
  endpoints:
    web:
      exposure:
        include: '*'
