logging:
  level:
    root: debug
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://quiet-star-2981.getsandbox.com:443
          predicates:
            - Path=/{segment}

