spring:
  boot:
    admin:
      client:
        url: ${sandbox.services.spring-boot-admin.url}
        instance:
          service-base-url: http://localhost:${server.port}
---
spring.config.activate.on-cloud-platform: kubernetes
spring.boot.admin.client.instance.service-base-url: http://${spring.application.name}:${server.port:8080}