spring:
  application:
    name: spring-boot-postgresql
  config:
    import:
      - shared/for-microservices.yaml
      - features/data_jpa.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/sandbox"
    username: "sandbox"
    password: "sandbox"