spring:
  application:
    name: spring-boot
  config:
    import:
      - shared/for-microservices.yaml
      - features/dynamic_properties.yaml
      - features/metrics.yaml
      - features/properties_conversion.yaml